<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBProduct.UI.Common\DBProduct.UI.Common.csproj" />
    <ProjectReference Include="..\DBProduct.UI.ViewModel\DBProduct.UI.ViewModel.csproj" />
  </ItemGroup>

</Project>
